-- Synthetic local fixtures only; all writes roll back.
BEGIN;
SET LOCAL statement_timeout='20s';
CREATE TEMP TABLE IF NOT EXISTS judge_before_functions AS SELECT oid,prosrc,proowner,proacl,prosecdef,proconfig FROM pg_proc;
CREATE TEMP TABLE IF NOT EXISTS judge_before_policies AS SELECT * FROM pg_policy;
CREATE TEMP TABLE judge_assertions(label text PRIMARY KEY);
CREATE FUNCTION pg_temp.judge_ok(value boolean,label text) RETURNS void LANGUAGE plpgsql AS $$BEGIN IF value IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL %',label;END IF;INSERT INTO judge_assertions VALUES(label);END$$;
DO $test$
DECLARE a constant uuid:='970f08d1-c1b8-572b-ad42-00277c8facbb';bot constant uuid:='e7c595cb-ff44-5611-aff1-44fb0ca8bf58';other constant uuid:='c0195ccd-de1e-5102-ad9c-d5bf4493f493';au uuid:=gen_random_uuid();bu uuid:=gen_random_uuid();ou uuid:=gen_random_uuid();m uuid:=gen_random_uuid();wrong uuid:=gen_random_uuid();room uuid;mid uuid;r record;k uuid:=gen_random_uuid();completion_key uuid:=gen_random_uuid();rev integer;ar integer;br integer;available jsonb;candidates jsonb;start_at timestamptz:=now()+interval '1 day';end_at timestamptz:=now()+interval '1 day 1 hour';relation text;count_before integer;
BEGIN
 PERFORM pg_temp.judge_ok(NOT EXISTS(SELECT 1 FROM judge_before_functions b JOIN pg_proc p USING(oid) WHERE (b.proowner,b.proacl,b.prosecdef,b.proconfig) IS DISTINCT FROM (p.proowner,p.proacl,p.prosecdef,p.proconfig)),'existing function owner ACL settings preserved');
 PERFORM pg_temp.judge_ok(NOT EXISTS(SELECT 1 FROM judge_before_functions b JOIN pg_proc p USING(oid) WHERE b.prosrc IS DISTINCT FROM p.prosrc AND p.oid<>'wingward_private.synthetic_matching_member(uuid)'::regprocedure),'old normal and recording RPC bodies unchanged');
 PERFORM pg_temp.judge_ok(NOT EXISTS((SELECT * FROM judge_before_policies EXCEPT SELECT * FROM pg_policy) UNION ALL (SELECT * FROM pg_policy EXCEPT SELECT * FROM judge_before_policies)),'existing RLS policies unchanged');
 PERFORM pg_temp.judge_ok(NOT has_function_privilege('anon','public.advance_judge_counterpart(uuid,uuid,text,integer,uuid)','execute') AND NOT has_function_privilege('authenticated','public.advance_judge_counterpart(uuid,uuid,text,integer,uuid)','execute') AND has_function_privilege('service_role','public.advance_judge_counterpart(uuid,uuid,text,integer,uuid)','execute'),'counterpart service-only execution');
 FOREACH relation IN ARRAY ARRAY['judge_counterpart_operations','judge_simulated_meetups'] LOOP
  PERFORM pg_temp.judge_ok((SELECT relrowsecurity FROM pg_class WHERE oid=('wingward_private.'||relation)::regclass) AND NOT has_table_privilege('anon','wingward_private.'||relation,'select') AND NOT has_table_privilege('authenticated','wingward_private.'||relation,'select') AND NOT has_table_privilege('service_role','wingward_private.'||relation,'select'),relation||' RLS private ACL');
 END LOOP;
 INSERT INTO auth.users(id,email,raw_app_meta_data,email_confirmed_at) VALUES(au,'judge-counterpart-actor-test@example.invalid',jsonb_build_object('wingward_judge_cohort','shipaton-20261001','wingward_judge_slot','judge01','wingward_judge_profile_id',a),now()),(bu,'new-peer-test@example.invalid','{}',now()),(ou,'wrong-peer-test@example.invalid','{}',now());
 UPDATE public.user_profiles SET id=CASE WHEN auth_user_id=au THEN a WHEN auth_user_id=bu THEN bot ELSE other END,birth_date='1990-01-01',age_verified_at=now(),age_verification_method='self_declared',onboarding_settings_completed_at=now(),gender_identity='nonbinary',preferred_genders=ARRAY['nonbinary'],preference_mode='selected',dating_market='JP',identity_verification_status='verified',identity_verified_at=now() WHERE auth_user_id IN(au,bu,ou);
 INSERT INTO wingward_private.judge_accounts(slot,actor_user_id,auth_user_id,counterpart_user_id,account_kind,issued_at,expires_at) VALUES('judge01',a,au,bot,'judge',now()-interval '1 minute',now()+interval '1 day');
 INSERT INTO public.matches(id,user_a_id,user_b_id,status) VALUES(m,least(a,bot),greatest(a,bot),'direct_chat_requested'),(wrong,least(a,other),greatest(a,other),'direct_chat_requested');
 INSERT INTO public.chat_requests(match_id,requester_id,responder_id,expires_at) VALUES(m,a,bot,now()+interval '1 day'),(wrong,a,other,now()+interval '1 day');
 SELECT * INTO r FROM public.advance_judge_counterpart(other,m,'accept',0,k);PERFORM pg_temp.judge_ok(r.outcome='denied','unregistered actor denied');
 SELECT * INTO r FROM public.advance_judge_counterpart(a,wrong,'accept',0,k);PERFORM pg_temp.judge_ok(r.outcome='not_found' AND NOT EXISTS(SELECT 1 FROM public.direct_chat_rooms WHERE match_id=wrong),'nonregistry counterpart denied without mutation');
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'unknown',0,k);PERFORM pg_temp.judge_ok(r.outcome='invalid_input','closed operation validation');
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'accept',1,k);PERFORM pg_temp.judge_ok(r.outcome='stale_revision','stale shared revision denied');
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'accept',0,k);room:=r.room_id;PERFORM pg_temp.judge_ok(r.outcome='ok' AND (SELECT status='accepted' FROM public.chat_requests WHERE match_id=m) AND (SELECT status='direct_chat_active' FROM public.matches WHERE id=m),'exact requester and peer accept atomic');
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'accept',0,k);PERFORM pg_temp.judge_ok(r.outcome='replayed' AND r.room_id=room AND (SELECT count(*)=1 FROM public.direct_chat_rooms WHERE match_id=m),'accept replay preserves one room');
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'intent',0,k);PERFORM pg_temp.judge_ok(r.outcome='idempotency_conflict','key cannot change operation');
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'intent',0,gen_random_uuid());PERFORM pg_temp.judge_ok(r.outcome='invalid_state' AND NOT EXISTS(SELECT 1 FROM public.chat_meetup_private_decisions WHERE match_id=m),'peer cannot invent actor intent');
 SELECT * INTO r FROM public.apply_chat_meetup_action(room,a,0,0,gen_random_uuid(),repeat('a',64),'{"type":"intent","value":"yes"}');PERFORM pg_temp.judge_ok(r.outcome='ok','actor normal intent');
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'intent',0,gen_random_uuid());mid:=r.meetup_id;rev:=r.revision;PERFORM pg_temp.judge_ok(r.outcome='ok' AND r.status='awaiting_availability','peer normal intent');
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'availability',rev,gen_random_uuid());PERFORM pg_temp.judge_ok(r.outcome='invalid_state' AND NOT EXISTS(SELECT 1 FROM public.chat_meetup_availability WHERE meetup_id=mid),'peer cannot invent actor availability');
 SELECT private_revision INTO ar FROM public.chat_meetup_private_decisions WHERE match_id=m AND user_id=a;
 available:=jsonb_build_object('type','availability.submit','source','manual','window',jsonb_build_object('starts_at',start_at,'ends_at',end_at+interval '2 hours'),'available',jsonb_build_array(jsonb_build_object('starts_at',start_at,'ends_at',end_at+interval '2 hours')));
 SELECT * INTO r FROM public.apply_chat_meetup_action(room,a,rev,ar,gen_random_uuid(),repeat('b',64),available);PERFORM pg_temp.judge_ok(r.outcome='ok','actor normal availability');
 UPDATE public.user_profiles SET identity_verification_status='none',identity_verified_at=NULL WHERE id=bot;
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'availability',rev,gen_random_uuid());PERFORM pg_temp.judge_ok(r.outcome='identity_verification_required' AND NOT EXISTS(SELECT 1 FROM public.chat_meetup_availability WHERE meetup_id=mid AND user_id=bot),'peer normal IDV gate and atomic rollback');
 UPDATE public.user_profiles SET identity_verification_status='verified',identity_verified_at=now() WHERE id=bot;
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'availability',rev,gen_random_uuid());PERFORM pg_temp.judge_ok(r.outcome='ok' AND (SELECT quota_claim_owner_id=a FROM public.chat_meetup_sessions WHERE meetup_id=mid) AND (SELECT count(*)=2 FROM public.chat_meetup_availability WHERE meetup_id=mid),'normal peer availability judge owns quota claim');
 SELECT * INTO r FROM public.claim_meetup_arrangement(mid,a,false,'judge-local-quota');PERFORM pg_temp.judge_ok(r.outcome='claimed' AND (SELECT used_count=1 FROM public.usage_counters WHERE user_id=a AND quota_key='meetup_arrange'),'normal quota consumed for judge');
 SELECT private_revision INTO ar FROM public.chat_meetup_private_decisions WHERE match_id=m AND user_id=least(a,bot);SELECT private_revision INTO br FROM public.chat_meetup_private_decisions WHERE match_id=m AND user_id=greatest(a,bot);
 candidates:=jsonb_build_array(jsonb_build_object('id','judge-t1','starts_at',start_at,'ends_at',end_at,'timezone','UTC'));
 SELECT * INTO r FROM public.publish_chat_meetup_times(room,a,rev,ar,br,candidates,NULL);rev:=r.revision;PERFORM pg_temp.judge_ok(r.outcome='ok' AND r.status='time_proposed','normal time proposal after quota');
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'time_approve',rev,gen_random_uuid());PERFORM pg_temp.judge_ok(r.outcome='invalid_state','peer cannot choose before actor');
 SELECT private_revision INTO ar FROM public.chat_meetup_private_decisions WHERE match_id=m AND user_id=a;
 SELECT * INTO r FROM public.apply_chat_meetup_action(room,a,rev,ar,gen_random_uuid(),repeat('c',64),'{"type":"time.approve","candidate_id":"judge-t1"}');PERFORM pg_temp.judge_ok(r.outcome='ok','actor normal time approval');
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'time_approve',rev,gen_random_uuid());rev:=r.revision;PERFORM pg_temp.judge_ok(r.outcome='ok' AND r.status='confirmed' AND (SELECT confirmed_starts_at=start_at AND confirmed_ends_at=end_at FROM public.chat_meetup_sessions WHERE meetup_id=mid),'peer approval preserves exact future approved time');
 SELECT private_revision INTO ar FROM public.chat_meetup_private_decisions WHERE match_id=m AND user_id=a;
 SELECT * INTO r FROM public.apply_chat_meetup_action(room,a,rev,ar,gen_random_uuid(),repeat('d',64),'{"type":"meeting.complete"}');PERFORM pg_temp.judge_ok(r.outcome='invalid_state','ordinary completion cannot bypass future end');
 SELECT * INTO r FROM public.apply_chat_meetup_action(room,a,rev,ar,completion_key,repeat('e',64),'{"type":"time.approve","candidate_id":"judge-t1"}');
 -- Direct normal RPC invalid state does not reserve completion key; seed a conflicting prior receipt to test atomic rollback.
 INSERT INTO public.chat_meetup_operations(room_id,user_id,idempotency_key,meetup_id,request_digest,outcome,result_status,result_revision) VALUES(room,a,completion_key,mid,repeat('f',64),'ok','confirmed',rev);
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'simulate_completion',rev,completion_key);PERFORM pg_temp.judge_ok(r.outcome='idempotency_conflict' AND NOT EXISTS(SELECT 1 FROM wingward_private.judge_simulated_meetups) AND (SELECT confirmed_starts_at=start_at AND confirmed_ends_at=end_at FROM public.chat_meetup_sessions WHERE meetup_id=mid),'nested normal failure restores timestamps and ledger');
 completion_key:=gen_random_uuid();
 UPDATE public.chat_meetup_private_decisions SET time_choice_id=NULL WHERE match_id=m AND user_id=bot;
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'simulate_completion',rev,gen_random_uuid());PERFORM pg_temp.judge_ok(r.outcome='invalid_state' AND NOT EXISTS(SELECT 1 FROM wingward_private.judge_simulated_meetups),'simulation requires both actual approvals');
 UPDATE public.chat_meetup_private_decisions SET time_choice_id='judge-t1' WHERE match_id=m AND user_id=bot;
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'simulate_completion',rev,completion_key);PERFORM pg_temp.judge_ok(r.outcome='ok' AND r.status='completed' AND (SELECT completed_a_at IS NOT NULL AND completed_b_at IS NOT NULL AND confirmed_ends_at<clock_timestamp() FROM public.chat_meetup_sessions WHERE meetup_id=mid),'explicit simulation runs normal actor and peer completion');
 PERFORM pg_temp.judge_ok((SELECT original_starts_at=start_at AND original_ends_at=end_at AND original_candidate_id='judge-t1' FROM wingward_private.judge_simulated_meetups WHERE meetup_id=mid),'original approval immutable in private simulation ledger');
 PERFORM pg_temp.judge_ok((SELECT count(*)=1 FROM public.chat_meetup_events WHERE meetup_id=mid AND event_key='judge:simulated-meetup' AND text LIKE 'Simulated meetup%no real meeting took place.'),'visible simulated disclosure');
 SELECT * INTO r FROM public.get_meetup_reflection_state(mid,a);PERFORM pg_temp.judge_ok(r.outcome='ok','normal reflection gate accepts own simulated completion');
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'simulate_completion',rev,completion_key);PERFORM pg_temp.judge_ok(r.outcome='replayed' AND (SELECT count(*)=1 FROM wingward_private.judge_simulated_meetups),'simulation exact replay');
 UPDATE wingward_private.judge_accounts SET expires_at=now()-interval '1 second' WHERE actor_user_id=a;
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'simulate_completion',rev,completion_key);PERFORM pg_temp.judge_ok(r.outcome='expired','expired replay denied');
 UPDATE wingward_private.judge_accounts SET expires_at=now()+interval '1 day',disabled_at=now() WHERE actor_user_id=a;
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'simulate_completion',rev,completion_key);PERFORM pg_temp.judge_ok(r.outcome='expired','disabled replay denied');
 UPDATE wingward_private.judge_accounts SET disabled_at=NULL WHERE actor_user_id=a;
 INSERT INTO public.blocks(blocker_id,blocked_id) VALUES(bot,a);
 SELECT * INTO r FROM public.advance_judge_counterpart(a,m,'simulate_completion',rev,completion_key);PERFORM pg_temp.judge_ok(r.outcome='not_found','postoperation block closes replay');
 PERFORM pg_temp.judge_ok((SELECT prior_spend_usd_micros IS NULL AND reserved_usd_micros=0 FROM wingward_private.judge_provider_budget) AND NOT EXISTS(SELECT 1 FROM wingward_private.judge_provider_policies),'budget stays unknown and all paid policies closed');
 EXECUTE 'SET LOCAL ROLE authenticated';BEGIN PERFORM public.advance_judge_counterpart(a,m,'accept',0,gen_random_uuid());RAISE EXCEPTION 'client called service RPC';EXCEPTION WHEN insufficient_privilege THEN NULL;END;EXECUTE 'RESET ROLE';PERFORM pg_temp.judge_ok(true,'actual authenticated RPC rejected');
END $test$;
SELECT count(*) AS passed_assertions FROM judge_assertions;

ROLLBACK;
