import {describe,it,expect,vi} from "vitest";
import {JudgeRealtimeCallController,judgeRealtimeStartSchema,type JudgeRealtimeLease,type JudgeRealtimeSideband} from "./judge-realtime-call";
const owner="11111111-1111-4111-8111-111111111111",session="22222222-2222-4222-8222-222222222222",reservation="33333333-3333-4333-8333-333333333333",now=Date.parse("2026-10-01T00:00:00Z");
function fixture(overrides:Record<string,unknown>={}){
 let time=now,lease:JudgeRealtimeLease|undefined,alarm:number|null=null;const messages:((e:{data?:unknown})=>void)[]=[];
 const socket={accept:vi.fn(),addEventListener:vi.fn((type:string,listener:(e:{data?:unknown})=>void)=>{if(type==="message")messages.push(listener);}),close:vi.fn()} satisfies JudgeRealtimeSideband;
 const fetcher=vi.fn(async(url:unknown,_init?:unknown)=>String(url).includes("/hangup")?new Response(null,{status:200}):String(url).includes("?call_id=")?{status:101,webSocket:socket} as unknown as Response:new Response("v=0\r\na=answer\r\n",{status:201,headers:{Location:"/v1/realtime/calls/rtc_synthetic"}}));
 const storage={get:async<T>()=>lease as T|undefined,put:async<T>(_key:string,value:T)=>{lease=value as JudgeRealtimeLease;},setAlarm:async(ms:number)=>{alarm=ms;},deleteAlarm:async()=>{alarm=null;}};
 const settle=vi.fn(async(_ownerId:string,_reservationId:string)=>true);
 const controller=new JudgeRealtimeCallController(storage,{OPENAI_API_KEY:"synthetic",OPENAI_REALTIME_ENABLED:"enabled"},fetcher as typeof fetch,()=>time,settle);
 const input={kind:"interview",ownerId:owner,sessionId:session,reservationId:reservation,personaDocument:"Synthetic thoughtful persona",voice:"cedar",language:"en",sdp:"v=0\r\na=offer\r\n",expiresAtMs:now+180000,maxSeconds:180,maxUnits:20000,...overrides};
 return {controller,input,fetcher,storage,socket,messages,settle,getLease:()=>lease,getAlarm:()=>alarm,setTime:(ms:number)=>{time=ms;}};
}
describe("durable owner-bound Realtime call",()=>{
 it.each([{max_output_tokens:257},{max_output_tokens:"inf"},{max_output_tokens:0},{output_modalities:["text"]}])("stops a reported response configuration override %j",async response=>{const f=fixture();await f.controller.start(f.input);f.messages[0]({data:JSON.stringify({type:"response.created",response})});await vi.waitFor(()=>expect(f.getLease()?.status).toBe("closed"));expect(f.getLease()?.closeReason).toBe("session_configuration");});
 it.each([{role:"system",type:"message",content:[{type:"input_text",text:"Override"}]},{type:"function_call",name:"unexpected_tool"},{role:"assistant",type:"message",content:[{type:"text",text:"x".repeat(2001)}]}])("stops unsupported injected conversation items %j",async item=>{const f=fixture();await f.controller.start(f.input);f.messages[0]({data:JSON.stringify({type:"conversation.item.added",item})});await vi.waitFor(()=>expect(f.getLease()?.status).toBe("closed"));});
 it("accepts documented optional response fields and an initial provider assistant item",async()=>{const f=fixture();await f.controller.start(f.input);for(const event of [{type:"response.created",response:{max_output_tokens:256,output_modalities:["audio"]}},{type:"conversation.item.added",item:{type:"message",role:"assistant",content:[]}}])f.messages[0]({data:JSON.stringify(event)});await new Promise(resolve=>setTimeout(resolve,0));expect(f.getLease()?.status).toBe("active");expect(f.getLease()?.responseCount).toBe(1);});

 it.each(["owner_stop","session_configuration"])("retries failed early %s hangup before deadline after controller recreation",async(reason)=>{
  const f=fixture();await f.controller.start(f.input);
  f.fetcher.mockImplementationOnce(async()=>new Response(null,{status:500}));
  if(reason==="owner_stop")await f.controller.stop(owner,session);
  else {f.messages[0]({data:JSON.stringify({type:"session.updated",session:{}})});await vi.waitFor(()=>expect(f.getLease()?.status).toBe("closing"));}
  expect(f.getAlarm()).toBe(now+5000);expect(f.settle).not.toHaveBeenCalled();
  const recreated=new JudgeRealtimeCallController(f.storage,{OPENAI_API_KEY:"synthetic",OPENAI_REALTIME_ENABLED:"enabled"},f.fetcher as typeof fetch,()=>now+5000,f.settle);
  await recreated.alarm();
  expect(f.fetcher.mock.calls.filter(call=>String(call[0]).endsWith("/hangup"))).toHaveLength(2);
  expect(f.getLease()).toMatchObject({status:"closed",settled:true,closeReason:reason});
  expect(f.settle.mock.calls).toEqual([[owner,reservation]]);expect(f.getAlarm()).toBeNull();
 });
 it("settles only exact owner and reservation after provider hangup",async()=>{const f=fixture();await f.controller.start(f.input);expect(f.settle).not.toHaveBeenCalled();await f.controller.stop(owner,session);expect(f.settle.mock.calls).toEqual([[owner,reservation]]);});
 it("existing lease rejection never attests that its provider did not start",async()=>{const f=fixture();await f.controller.start(f.input);const response=await f.controller.start(f.input);expect(response.status).toBe(409);expect(await response.json()).not.toHaveProperty("providerNotStarted");expect(f.settle).not.toHaveBeenCalled();});
 it("busy creation rejection never attests no provider for the concurrent attempt",async()=>{const f=fixture();let finish!:(value:Response)=>void;f.fetcher.mockImplementationOnce(()=>new Promise<Response>(resolve=>{finish=resolve;}));const pending=f.controller.start(f.input);await vi.waitFor(()=>expect(f.fetcher).toHaveBeenCalledOnce());const response=await f.controller.start(f.input);expect(response.status).toBe(409);expect(await response.json()).not.toHaveProperty("providerNotStarted");expect(f.settle).not.toHaveBeenCalled();finish(new Response(null,{status:400}));await pending;expect(f.settle.mock.calls).toEqual([[owner,reservation]]);});
 it("drops the prototype mutation key from confirmed traits before building provider input",()=>{const f=fixture({confirmedTraits:JSON.parse('{"__proto__":"slow"}')});const parsed=judgeRealtimeStartSchema.safeParse(f.input);expect(parsed.success).toBe(true);if(parsed.success){expect(Object.hasOwn(parsed.data.confirmedTraits,"__proto__")).toBe(false);expect(parsed.data.confirmedTraits).toEqual({});}});
 it("sends fixed server config and returns only SDP, persists deadline",async()=>{const f=fixture(),r=await f.controller.start(f.input);expect(r.status).toBe(201);const body=await r.json();expect(body).toEqual({sdp:"v=0\r\na=answer\r\n",max_duration_seconds:180});expect(f.getAlarm()).toBe(now+180000);const config=JSON.parse(((f.fetcher.mock.calls[0][1] as RequestInit).body as FormData).get("session") as string);expect(config.model).toBe("gpt-realtime-2.1-mini");expect(config.max_output_tokens).toBe(256);expect(config.tools).toEqual([]);expect(f.socket.accept).toHaveBeenCalledOnce();expect(body).not.toHaveProperty("client_secret");});
 it("returns only owner-bound safe lease facts without IDs or provider calls",async()=>{
  const f=fixture();expect(await(await f.controller.readStatus(owner,session)).json()).toEqual({leaseExists:false,status:"missing",providerCreated:false,settled:false,closeReason:null});expect(f.fetcher).not.toHaveBeenCalled();
  await f.controller.start(f.input);const before=f.fetcher.mock.calls.length;expect(await(await f.controller.readStatus(owner,session)).json()).toEqual({leaseExists:true,status:"active",providerCreated:true,settled:false,closeReason:null});expect((await f.controller.readStatus(session,session)).status).toBe(404);expect(f.fetcher.mock.calls.length).toBe(before);
 });
 it("records only a fixed configuration failure reason and preserves it through stop",async()=>{const f=fixture();await f.controller.start(f.input);const config=JSON.parse(((f.fetcher.mock.calls[0][1] as RequestInit).body as FormData).get("session") as string);config.instructions="Private canary must never persist";f.messages[0]({data:JSON.stringify({type:"session.created",session:config})});await new Promise(resolve=>setTimeout(resolve,0));await f.controller.stop(owner,session);const status=await(await f.controller.readStatus(owner,session)).json() as {closeReason:string|null;status:string};expect(status.closeReason).toBe("session_configuration");expect(status.status).toBe("closed");expect(JSON.stringify(f.getLease())).not.toContain("Private canary");expect((await f.controller.readStatus(session,session)).status).toBe(404);});
 it("accepts an unchanged real-shaped provider session configuration",async()=>{const f=fixture();await f.controller.start(f.input);const config=JSON.parse(((f.fetcher.mock.calls[0][1] as RequestInit).body as FormData).get("session") as string);f.messages[0]({data:JSON.stringify({type:"session.created",session:config})});await new Promise(resolve=>setTimeout(resolve,0));expect(f.getLease()?.status).toBe("active");expect(f.getLease()?.closeReason).toBeUndefined();});
 it("uses the global receiver for create, sideband and hangup as required by workerd",async()=>{const f=fixture();await f.controller.start(f.input);await f.controller.stop(owner,session);expect(f.fetcher.mock.contexts).toEqual([globalThis,globalThis,globalThis]);});
 it("settles only the exact expired legacy no-call diagnostic without another provider call",async()=>{
  const f=fixture();const legacy={ownerId:"56f96c3d-6040-5c57-b6ad-c59284ba4f3c",sessionId:"124ea7e7-1cd0-4965-8198-9162b6fb94b4",reservationId:reservation,deadlineMs:now-1,callId:null,status:"closing" as const};await f.storage.put("lease",legacy);
  expect(await(await f.controller.stop(legacy.ownerId,legacy.sessionId)).json()).toEqual({closed:true});expect(f.getLease()?.status).toBe("closed");expect(f.getLease()?.settled).toBe(true);expect(f.getAlarm()).toBeNull();expect(f.fetcher).not.toHaveBeenCalled();
 });
 it.each([{runtimeTransportVersion:1},{ownerId:owner},{sessionId:session},{deadlineMs:now+1000},{status:"active"}])("never treats another or versioned failure as the legacy diagnostic %j",async changes=>{
  const f=fixture();const lease={ownerId:"56f96c3d-6040-5c57-b6ad-c59284ba4f3c",sessionId:"124ea7e7-1cd0-4965-8198-9162b6fb94b4",reservationId:reservation,deadlineMs:now-1,callId:null,status:"closing" as const,...changes};await f.storage.put("lease",lease);
  expect(await(await f.controller.stop(lease.ownerId,lease.sessionId)).json()).toEqual({closed:false});expect(f.getLease()?.settled).not.toBe(true);expect(f.fetcher).not.toHaveBeenCalled();
 });
 it("a legacy-shaped lease with a provider call must use hangup before settlement",async()=>{
  const f=fixture();const lease={ownerId:"56f96c3d-6040-5c57-b6ad-c59284ba4f3c",sessionId:"124ea7e7-1cd0-4965-8198-9162b6fb94b4",reservationId:reservation,deadlineMs:now-1,callId:"rtc_live",status:"closing" as const};await f.storage.put("lease",lease);
  f.fetcher.mockImplementationOnce(async()=>new Response(null,{status:503}));expect(await(await f.controller.stop(lease.ownerId,lease.sessionId)).json()).toEqual({closed:false});expect(f.getLease()?.settled).not.toBe(true);expect(f.fetcher.mock.calls[0][0]).toBe("https://api.openai.com/v1/realtime/calls/rtc_live/hangup");
 });
 it("replay after recreation cannot mint or extend deadline",async()=>{const f=fixture();await f.controller.start(f.input);const recreated=new JudgeRealtimeCallController(f.storage,{OPENAI_API_KEY:"synthetic",OPENAI_REALTIME_ENABLED:"enabled"},f.fetcher as typeof fetch,()=>now+10000,async()=>true);expect((await recreated.start(f.input)).status).toBe(409);expect(f.fetcher).toHaveBeenCalledTimes(2);expect(f.getAlarm()).toBe(now+180000);});
 it("another owner cannot stop the call",async()=>{const f=fixture();await f.controller.start(f.input);expect((await f.controller.stop(session,session)).status).toBe(404);expect(f.fetcher).toHaveBeenCalledTimes(2);});
 it("alarm after recreation ends the exact provider call",async()=>{const f=fixture();await f.controller.start(f.input);const recreated=new JudgeRealtimeCallController(f.storage,{OPENAI_API_KEY:"synthetic",OPENAI_REALTIME_ENABLED:"enabled"},f.fetcher as typeof fetch,()=>now+180000,async()=>true);await recreated.alarm();expect(f.getLease()?.status).toBe("closed");expect(f.getAlarm()).toBeNull();expect(f.fetcher.mock.calls[2][0]).toBe("https://api.openai.com/v1/realtime/calls/rtc_synthetic/hangup");});
 it("hangup failure keeps lease and durable retry",async()=>{const f=fixture();await f.controller.start(f.input);f.fetcher.mockImplementationOnce(async()=>new Response("provider private error",{status:500}));f.setTime(now+180000);await f.controller.alarm();expect(f.getLease()?.status).toBe("closing");expect(f.getAlarm()).toBe(now+185000);expect((await f.controller.start(f.input)).status).toBe(409);});
 it("account expiry shortens call",async()=>{const f=fixture({expiresAtMs:now+60000});expect((await f.controller.start(f.input)).status).toBe(201);expect(f.getAlarm()).toBe(now+60000);});
 it.each([{maxSeconds:181},{expiresAtMs:now+1000},{sdp:"secret"},{kind:"untrusted"},{confirmedTraits:{custom:"private"}}])("invalid input never invokes provider %j",async bad=>{const f=fixture(bad);expect((await f.controller.start(f.input)).status).not.toBe(201);expect(f.fetcher).not.toHaveBeenCalled();});
 it("attests no provider when remaining deadline is too short before lease creation",async()=>{const f=fixture({expiresAtMs:now+14000});const response=await f.controller.start(f.input);expect(response.status).toBe(409);expect(await response.json()).toEqual({error:"Voice interview unavailable",providerNotStarted:true});expect(f.fetcher).not.toHaveBeenCalled();expect(f.getLease()).toBeUndefined();});
 it("rejects a foreign provider Location",async()=>{const f=fixture();f.fetcher.mockImplementationOnce(async()=>new Response("v=0",{status:201,headers:{Location:"https://attacker.invalid/v1/realtime/calls/rtc_synthetic"}}));expect((await f.controller.start(f.input)).status).toBe(503);expect(f.fetcher).toHaveBeenCalledTimes(1);});
 it.each([400,401,403,404,413,422,429])("settles explicit provider rejection %s without a hangup call",async code=>{const f=fixture();f.fetcher.mockImplementationOnce(async()=>new Response(null,{status:code}));expect((await f.controller.start(f.input)).status).toBe(503);expect(f.getLease()?.status).toBe("closed");expect(f.getLease()?.settled).toBe(true);expect(f.getLease()?.closeReason).toBe("provider_create_rejected");expect(f.getAlarm()).toBeNull();expect(f.fetcher).toHaveBeenCalledOnce();});
 it.each([302,408,409,500,503,201])("keeps ambiguous provider creation %s blocked without endless retry alarms",async code=>{const f=fixture();f.fetcher.mockImplementationOnce(async()=>new Response(null,{status:code}));expect((await f.controller.start(f.input)).status).toBe(503);expect(f.getLease()?.status).toBe("closing");expect(f.getLease()?.settled).not.toBe(true);expect(f.getLease()?.closeReason).toBe("provider_create_unknown");expect(f.getAlarm()).toBeNull();expect((await f.controller.start(f.input)).status).toBe(409);expect(f.fetcher).toHaveBeenCalledOnce();});
 it.each(["constructor","toString"])("rejects prototype trait %s without throwing or invoking provider",async key=>{const f=fixture({confirmedTraits:JSON.parse(`{"${key}":"slow"}`)});const response=await f.controller.start(f.input);expect(response.status).toBe(503);expect(await response.json()).toHaveProperty("providerNotStarted",true);expect(f.fetcher).not.toHaveBeenCalled();});
 it("keeps an unclassified old no-call lease blocked without perpetual alarms",async()=>{const f=fixture();await f.storage.put("lease",{ownerId:owner,sessionId:session,reservationId:reservation,deadlineMs:now-1,callId:null,status:"closing",runtimeTransportVersion:1});await f.controller.alarm();expect(f.getLease()?.settled).not.toBe(true);expect(f.getAlarm()).toBeNull();expect(f.fetcher).not.toHaveBeenCalled();});
 it("preserves uncertain timeout for reconciliation and never assumes no provider call",async()=>{const f=fixture();f.fetcher.mockRejectedValueOnce(new Error("synthetic timeout"));expect((await f.controller.start(f.input)).status).toBe(503);expect(f.getLease()?.providerCreateState).toBe("unknown");expect(f.getLease()?.settled).not.toBe(true);expect(f.getAlarm()).toBeNull();});
 it("failed sideband stops provider before exposing SDP",async()=>{const f=fixture();f.fetcher.mockImplementation(async(url:unknown)=>String(url).includes("?call_id=")?new Response(null,{status:503}):String(url).includes("/hangup")?new Response(null,{status:200}):new Response("v=0",{status:201,headers:{Location:"/v1/realtime/calls/rtc_synthetic"}}));expect((await f.controller.start(f.input)).status).toBe(503);expect(f.getLease()?.status).toBe("closed");});
 it("client output cap escalation causes hangup",async()=>{const f=fixture();await f.controller.start(f.input);f.messages[0]({data:JSON.stringify({type:"session.updated",session:{model:"gpt-realtime-2.1-mini",max_output_tokens:32768,tools:[],output_modalities:["audio"]}})});await new Promise(resolve=>setTimeout(resolve,0));expect(f.getLease()?.status).toBe("closed");});
 it("excess response creation causes hangup",async()=>{const f=fixture();await f.controller.start(f.input);for(let i=0;i<21;i++)f.messages[0]({data:JSON.stringify({type:"response.created",response:{id:`synthetic_${i}`}})});await new Promise(resolve=>setTimeout(resolve,0));expect(f.getLease()?.responseCount).toBe(21);expect(f.getLease()?.status).toBe("closed");});
 it("legitimate native final-commit VAD shutdown retains fixed caps",async()=>{const f=fixture();await f.controller.start(f.input);const config=JSON.parse(((f.fetcher.mock.calls[0][1] as RequestInit).body as FormData).get("session") as string);config.audio.input.turn_detection=null;f.messages[0]({data:JSON.stringify({type:"session.updated",session:config})});await new Promise(resolve=>setTimeout(resolve,0));expect(f.getLease()?.status).toBe("active");});
 it("a client cannot widen the configured input window",async()=>{const f=fixture();await f.controller.start(f.input);const config=JSON.parse(((f.fetcher.mock.calls[0][1] as RequestInit).body as FormData).get("session") as string);config.truncation.token_limits.post_instructions=128000;f.messages[0]({data:JSON.stringify({type:"session.updated",session:config})});await new Promise(resolve=>setTimeout(resolve,0));expect(f.getLease()?.status).toBe("closed");});
 it("a client cannot replace server instructions",async()=>{const f=fixture();await f.controller.start(f.input);const config=JSON.parse(((f.fetcher.mock.calls[0][1] as RequestInit).body as FormData).get("session") as string);config.instructions="Attacker controlled instructions";f.messages[0]({data:JSON.stringify({type:"session.updated",session:config})});await new Promise(resolve=>setTimeout(resolve,0));expect(f.getLease()?.status).toBe("closed");});
 it("token unit cap remains enforced without calculating currency",async()=>{const f=fixture();await f.controller.start(f.input);f.messages[0]({data:JSON.stringify({type:"response.done",response:{usage:{total_tokens:50000,input_tokens:50000,output_tokens:0}}})});await new Promise(resolve=>setTimeout(resolve,0));expect(f.getLease()?.observedUnits).toBe(50000);expect(f.getLease()).not.toHaveProperty("observedUsdMicros");expect(f.getLease()?.status).toBe("closed");});
 it("ignores former monetary estimate while keeping a valid call below token cap",async()=>{const f=fixture();await f.controller.start(f.input);await f.storage.put("lease",{...f.getLease(),observedUsdMicros:999999999});f.messages[0]({data:JSON.stringify({type:"response.done",response:{usage:{total_tokens:1,input_tokens:1,output_tokens:0}}})});await new Promise(resolve=>setTimeout(resolve,0));expect(f.getLease()?.status).toBe("active");expect(f.getLease()?.observedUnits).toBe(1);expect((f.getLease() as unknown as {observedUsdMicros:number}).observedUsdMicros).toBe(999999999);});
 it("token usage missing from provider cannot silently bypass controls",async()=>{const f=fixture();await f.controller.start(f.input);f.messages[0]({data:JSON.stringify({type:"response.done",response:{}})});await new Promise(resolve=>setTimeout(resolve,0));expect(f.getLease()?.status).toBe("closed");});
 it("closed provider still retries SQL acknowledgement and blocks restart",async()=>{const f=fixture();await f.controller.start(f.input);const recreated=new JudgeRealtimeCallController(f.storage,{OPENAI_API_KEY:"synthetic",OPENAI_REALTIME_ENABLED:"enabled"},f.fetcher as typeof fetch,()=>now+180000,async()=>false);await recreated.alarm();expect(f.getLease()?.status).toBe("closed");expect(f.getLease()?.settled).not.toBe(true);expect(f.getAlarm()).toBe(now+185000);});
 it("reflection uses reflection prompt without persisting private persona",async()=>{const f=fixture({kind:"reflection",confirmedTraits:{rhythm_preference:"slow"}});await f.controller.start(f.input);const config=JSON.parse(((f.fetcher.mock.calls[0][1] as RequestInit).body as FormData).get("session") as string);expect(config.instructions).toContain("post-meetup reflection");expect(f.getLease()).not.toHaveProperty("personaDocument");});
});
