import { Hono } from 'hono';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { Env } from '../env';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',C='44444444-4444-4444-8444-444444444444',M='33333333-3333-4333-8333-333333333333';
const mocks=vi.hoisted(()=>({getClient:vi.fn(),snapshot:vi.fn(),verified:vi.fn(),pair:vi.fn()}));
vi.mock('../db/client',()=>({getSupabaseClient:()=>mocks.getClient()}));
vi.mock('../middleware/auth',()=>({requireAuth:async(c:import('hono').Context,next:()=>Promise<void>)=>{c.set('user_id',c.req.header('x-test-user')??'11111111-1111-4111-8111-111111111111');await next();},requireAgeVerified:async(_c:unknown,next:()=>Promise<void>)=>next()}));
vi.mock('../services/match-age-access',()=>({filterVerifiedMatches:(...args:unknown[])=>mocks.verified(...args),checkVerifiedPair:(...args:unknown[])=>mocks.pair(...args)}));
vi.mock('../services/matching-current-access',()=>({MAX_MATCHING_CURRENT_SNAPSHOT_EXPECTATIONS:128,readMatchingCurrentSnapshot:(...args:unknown[])=>mocks.snapshot(...args)}));
vi.mock('../services/onboarding-settings',()=>({getProfilePhotoAdapter:()=>({})}));
import matching from './matching';
const row={id:M,user_a_id:A,user_b_id:B,final_score:91,profile_score:88,conversation_score:94,status:'fox_conversation_completed',score_details:{summary:'Fictional'},created_at:'2026-09-30T20:00:00Z'};
const snapshot={...row,layer_scores:{},profile_a:{id:A,nickname:'Actor',avatar_url:null,avatar_storage_path:null},profile_b:{id:B,nickname:'Fictional peer',avatar_url:null,avatar_storage_path:null},compatibilityConversation:{id:C,status:'completed',purpose:'compatibility',match_id:M}};
const access={actorId:A,counterpartId:B,accountKind:'judge' as const,expiresAtMs:Date.parse('2026-10-13T19:00:00Z')};
function setup(rows:unknown[]=[row]){const traces:Array<{table:string;filters:unknown[]}>=[];const client={from(table:string){const trace={table,filters:[] as unknown[]};traces.push(trace);const q:Record<string,unknown>={};for(const m of ['select','in','eq','or','order','limit','lt'])q[m]=(...args:unknown[])=>{trace.filters.push([m,...args]);return q;};const data=()=>table==='matches'?rows:table==='personas'?[{user_id:B,icon_url:null}]:table==='fox_conversations'?[snapshot.compatibilityConversation]:[];q.then=(resolve:(r:unknown)=>unknown,reject:(r:unknown)=>unknown)=>Promise.resolve({data:data(),error:null}).then(resolve,reject);q.single=async()=>({data:table==='matches'?rows[0]:{nickname:'Fictional peer',avatar_url:null},error:null});q.maybeSingle=async()=>({data:null,error:null});return q;}};mocks.getClient.mockReturnValue(client);return{client,traces};}
function app(judge:typeof access|null=access){const a=new Hono<Env>();a.use('*',async(c,next)=>{if(judge)c.set('judge_access',judge);await next();});a.route('/api/matching',matching);return a;}
beforeEach(()=>{vi.clearAllMocks();setup();mocks.snapshot.mockResolvedValue({ok:true,rows:new Map([[M,snapshot]])});mocks.verified.mockImplementation(async(_c:unknown,rows:unknown[])=>({ok:true,rows}));mocks.pair.mockResolvedValue({ok:true});});
describe('judge exactpair native matching contract',()=>{
 it('reads registry pair directly in daily-results without global batch rows and marks trusted simulation',async()=>{const s=setup();const r=await app().request('/api/matching/daily-results?date=2001-01-01',{}, {BATCH_TIMEZONE:'Asia/Tokyo'});expect(r.status).toBe(200);expect((await r.json()) as unknown).toMatchObject({data:{batch_status:'completed',simulated_counterpart:true,matches:[{id:M,partner_id:B}],total_matches:1,conversations_completed:1}});expect(s.traces.map(t=>t.table)).toEqual(['matches']);expect(s.traces[0]?.filters).toContainEqual(['in','user_a_id',[A,B]]);expect(s.traces[0]?.filters).toContainEqual(['in','user_b_id',[A,B]]);expect(r.headers.get('cache-control')).toBe('private, no-store');});
 it('returns empty judge result without reading another cohort when pair has no match',async()=>{setup([]);mocks.snapshot.mockResolvedValue({ok:true,rows:new Map()});const r=await app().request('/api/matching/daily-results', {}, {});expect(await r.json()).toMatchObject({data:{matches:[],total_matches:0,simulated_counterpart:true}});});
 it.each([{...row,user_b_id:C},{...row,user_a_id:B,user_b_id:B}])('rejects out-of-pair query data before snapshot',async other=>{setup([other]);expect((await app().request('/api/matching/daily-results', {}, {})).status).toBe(503);expect(mocks.snapshot).not.toHaveBeenCalled();});
 it('rejects actor mismatch or expired access before peer query',async()=>{for(const context of [{...access,actorId:C},{...access,expiresAtMs:Date.now()-1}]){const s=setup();expect((await app(context).request('/api/matching/daily-results', {}, {})).status).toBe(503);expect(s.traces).toEqual([]);}});
 it('hides blocked or newly ineligible snapshots',async()=>{mocks.snapshot.mockResolvedValue({ok:true,rows:new Map()});const r=await app().request('/api/matching/daily-results', {}, {});expect(await r.json()).toMatchObject({data:{matches:[],total_matches:0}});});
 it('hides raw snapshot errors',async()=>{mocks.snapshot.mockRejectedValue(Error('PRIVATE-CANARY'));const r=await app().request('/api/matching/daily-results', {}, {});expect(r.status).toBe(503);expect(await r.text()).not.toContain('PRIVATE-CANARY');});
 it('applies pair query bounds to paginated results',async()=>{const s=setup();const r=await app().request('/api/matching/results');expect(r.status).toBe(200);expect(s.traces[0]?.filters).toContainEqual(['in','user_a_id',[A,B]]);expect(s.traces[0]?.filters).toContainEqual(['in','user_b_id',[A,B]]);});
 it('rejects out-of-pair results before age, block or peer reads',async()=>{const s=setup([{...row,user_b_id:C}]);expect((await app().request('/api/matching/results')).status).toBe(503);expect(s.traces.map(t=>t.table)).toEqual(['matches']);expect(mocks.verified).not.toHaveBeenCalled();});
 it('does not expose detail for another counterpart',async()=>{const s=setup([{...row,user_b_id:C}]);expect((await app().request(`/api/matching/results/${M}`)).status).toBe(404);expect(s.traces.map(t=>t.table)).toEqual(['matches']);expect(mocks.pair).not.toHaveBeenCalled();});
 it('marks matching detail only on trusted exactpair',async()=>{const r=await app().request(`/api/matching/results/${M}`);expect(r.status).toBe(200);expect(await r.json()).toMatchObject({data:{id:M,partner_id:B,simulated_counterpart:true}});});
 it('preserves ordinary daily path without a simulation marker',async()=>{const s=setup();const r=await app(null).request('/api/matching/daily-results', {}, {});expect(r.status).toBe(200);expect(s.traces[0]?.table).toBe('daily_match_pairs');expect(JSON.stringify(await r.json())).not.toContain('simulated_counterpart');});
});
