import { Hono } from "hono";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { Env } from "../env";
const resolve=vi.fn();
vi.mock("./auth",()=>({resolveAuthUser:(...args:unknown[])=>resolve(...args)}));
import { productionE2EGate, readProductionE2EConfig } from "./production-e2e-gate";
import {hasRecordingRehearsalConfig,readRecordingRehearsalConfig} from "../services/recording-rehearsal";
const REN="9d836fee-7b93-41ce-b577-34a63006aaea",MAYA="a88a89e2-5421-5ce9-a33b-76d512898c37",NOW=Date.parse("2026-10-01T01:00:00Z");
const ENV={RECORDING_REHEARSAL_ENABLED:"enabled",RECORDING_REHEARSAL_PAIR:"demo-maya-ren",RECORDING_REHEARSAL_ISSUED_AT:"2026-10-01T00:00:00Z",RECORDING_REHEARSAL_EXPIRES_AT:"2026-10-01T02:00:00Z",RECORDING_REHEARSAL_BILLING_ONLY:"enabled"};
function app(){const a=new Hono<Env>();a.use("*",productionE2EGate);a.all("*",c=>c.json({user_id:c.get("user_id"),read_only:c.get("production_e2e_read_only"),recording_config_injected:c.get("recording_rehearsal")!==undefined}));return a;}
const req=(path:string,method="GET",env=ENV)=>app().request(path,{method,headers:{Authorization:"Bearer fixture"}},env);
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(NOW);vi.clearAllMocks();resolve.mockResolvedValue({userId:REN,authUserId:"auth-fixture"});});afterEach(()=>vi.useRealTimers());
describe("billing-only recording gate",()=>{
 it.each([REN,MAYA])("authenticates exact cohort owner %s for four read-only routes",async owner=>{resolve.mockResolvedValue({userId:owner,authUserId:"auth-fixture"});for(const path of ["/api/auth/me","/api/profiles/me","/api/billing/identity","/api/billing/status"]){const r=await req(path);expect(r.status).toBe(200);expect(await r.json()).toEqual({user_id:owner,read_only:true,recording_config_injected:false});}});
 it("delegates exact vendor webhook to its independent authentication",async()=>{const r=await req("/api/webhooks/revenuecat","POST");expect(r.status).toBe(200);expect(resolve).not.toHaveBeenCalled();});
 it.each([["POST","/api/profiles/generate"],["GET","/api/speed-dating/sessions/22222222-2222-4222-8222-222222222222/native-bootstrap"],["POST","/api/profiles/me/confirm"],["POST","/api/recording-rehearsal/matching/start"],["POST","/api/meetup-reflections/22222222-2222-4222-8222-222222222222/bootstrap"],["POST","/api/webhooks/revenuecat/"],["GET","/api/billing/status/"],["POST","/api/billing/status"],["GET","/api/chat-meetups/rooms/22222222-2222-4222-8222-222222222222"],["POST","/api/testing/synthetic-session"]])("closes %s %s before provider/auth work",async(method,path)=>{expect((await req(path,method)).status).toBe(403);expect(resolve).not.toHaveBeenCalled();});
 it("does not admit another authenticated owner",async()=>{resolve.mockResolvedValue({userId:"11111111-1111-4111-8111-111111111111",authUserId:"other"});expect((await req("/api/billing/identity")).status).toBe(403);});
 it("keeps normal authentication failure",async()=>{resolve.mockResolvedValue(null);expect((await req("/api/billing/status")).status).toBe(401);});
 it("rechecks expiry after authenticated lookup",async()=>{resolve.mockImplementation(async()=>{vi.setSystemTime(Date.parse(ENV.RECORDING_REHEARSAL_EXPIRES_AT));return {userId:REN,authUserId:"auth"};});expect((await req("/api/billing/status")).status).toBe(503);});
 it.each(["enabled","disabled"])("preserves saved own profile after expiry with valid %s flag",async flag=>{vi.setSystemTime(Date.parse(ENV.RECORDING_REHEARSAL_EXPIRES_AT));for(const path of ["/api/auth/me","/api/profiles/me"])expect((await req(path,"GET",{...ENV,RECORDING_REHEARSAL_BILLING_ONLY:flag})).status).toBe(200);for(const [method,path]of [["GET","/api/billing/identity"],["GET","/api/billing/status"],["POST","/api/webhooks/revenuecat"]])expect((await req(path,method,{...ENV,RECORDING_REHEARSAL_BILLING_ONLY:flag})).status).toBe(503);});
 it.each([{RECORDING_REHEARSAL_BILLING_ONLY:"enable"},{RECORDING_REHEARSAL_PAIR:"sora-ren"},{RECORDING_REHEARSAL_OWNER_PREP_ONLY:"enabled",RECORDING_REHEARSAL_SYNTHETIC_TEST_ADMISSION_ID:undefined},{PRODUCTION_E2E_READ_ONLY:"true"},{RECORDING_REHEARSAL_SORA_PROFILE_REVISION_ENABLED:"enabled"}])("invalid or conflicting mode is closed %#",async overrides=>{for(const now of [NOW,Date.parse(ENV.RECORDING_REHEARSAL_EXPIRES_AT)]){vi.setSystemTime(now);for(const path of ["/api/profiles/me","/api/billing/status"])expect((await req(path,"GET",{...ENV,...overrides})).status).toBe(503);}expect(resolve).not.toHaveBeenCalled();});
 it("flag alone cannot fall through to ordinary provider/scheduled operation",()=>{const env={RECORDING_REHEARSAL_BILLING_ONLY:"enabled"};expect(hasRecordingRehearsalConfig(env)).toBe(true);expect(readRecordingRehearsalConfig(env)).toEqual({kind:"invalid"});expect(readProductionE2EConfig(env as Env["Bindings"])).toEqual({kind:"invalid"});});
});
